// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/Account/Me": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get information current User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Information",
                "responses": {}
            }
        },
        "/api/Account/SignIn": {
            "post": {
                "description": "login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "SignIn",
                "parameters": [
                    {
                        "description": "credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.InputUser"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/Account/SignOut": {
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "SignOut",
                "responses": {}
            }
        },
        "/api/Account/SignUp": {
            "post": {
                "description": "Create account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "SignUp",
                "parameters": [
                    {
                        "description": "account info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.User"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/Account/Update": {
            "put": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Edit the user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "description": "Update account",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.InputUser"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/Admin/Account": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get the list of users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Accounts",
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Admin update the user information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "UpdateAccount",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id of user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Admin create the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "CreateUser",
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Admin remove the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "DeleteUser",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id of user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Admin/Account/:id": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get the user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "GetAccount",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id of user",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Admin/Rent": {
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Create new rent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminNewRent",
                "responses": {}
            }
        },
        "/api/Admin/Rent/:id": {
            "put": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Update the rent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminUpdateRent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "rent id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Admin/Rent/:rentId": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get rent by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminGetRent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "rent id",
                        "name": "rentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Delete the rent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminDeleteRent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "rent id",
                        "name": "rentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Admin/Rent/End/:rentId": {
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "End the rent",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminEndRent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "rent id",
                        "name": "rentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Admin/Transport": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get all transports",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "GetTransports",
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Admin add the transport",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminAddTransport",
                "responses": {}
            }
        },
        "/api/Admin/Transport/:id": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get transport by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminGetTransport",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transport id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Admin update the transport information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminUpdateTransport",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transport id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Admin delete the transport",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminDeleteTransport",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transport id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Rent/:rentId": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get rent by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rent"
                ],
                "summary": "GetRent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "rent id",
                        "name": "rentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Rent/End/:rentId": {
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "End renting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rent"
                ],
                "summary": "End",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "rent id",
                        "name": "rentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "latitude of tranposrt",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "longitude of tranposrt",
                        "name": "long",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Rent/MyHistory": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get the user history of rents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rent"
                ],
                "summary": "MyHistory",
                "responses": {}
            }
        },
        "/api/Rent/New/:transportId": {
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Start renting",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rent"
                ],
                "summary": "StartRent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tranport id",
                        "name": "transportId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type of renting: minutes or days",
                        "name": "rentType",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/api/Rent/Transport": {
            "get": {
                "description": "Get transport which not far than radius from point",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rent"
                ],
                "summary": "GetTransport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "latitude of point",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "longitude of point",
                        "name": "long",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "radius",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type of transport",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Rent/TransportHistory/:trnaposrtId": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get history of transport",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rent"
                ],
                "summary": "TranposrtHistory",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transport id",
                        "name": "transportId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/Transport": {
            "post": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Create transport",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "CreateTransport",
                "parameters": [
                    {
                        "description": "Transport",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Transport"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/Transport/:id": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get information about transport",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "TransportInformation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transport id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "put": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Edit the Transport information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "UpdateTransport",
                "parameters": [
                    {
                        "description": "Transport",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.Transport"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "Transport id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Remove the Transport",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transport"
                ],
                "summary": "DeleteTransport",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transport id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/TransportHistory/:transportId": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get  transport history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminGetTransportHitory",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "transport id",
                        "name": "transportId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api/UserHistory/:userId": {
            "get": {
                "security": [
                    {
                        "ApKeyAuth": []
                    }
                ],
                "description": "Get user history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "AdminGetUserHistory",
                "responses": {}
            }
        }
    },
    "definitions": {
        "entities.Transport": {
            "type": "object",
            "properties": {
                "can_be_rented": {
                    "type": "boolean"
                },
                "color": {
                    "type": "string"
                },
                "day_price": {
                    "type": "number"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "identifier": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "minute_price": {
                    "type": "number"
                },
                "model": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "integer"
                },
                "transport_type": {
                    "type": "string"
                }
            }
        },
        "entities.User": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "balance": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.InputUser": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Rent Transport",
	Description:      "WEB API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
